baseurl: '/www'
exclude: ['README.md']
permalink: pretty
title: 'SCRATCh SecDevOps'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/secDevOps.png"
  desktop: "images/logo/secDevOps.png"
  desktop_height: "36px"
footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "SCRATCh SecDevOps"
  meta_og_type: "website"
  meta_og_url: "https://scratch-itea3.github.io/www/"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "SecDevOps ist just too difficult to start from scratch - better start with the SCRATCh knowledge."
  meta_twitter_card: "summary"
  meta_twitter_site: "@tillwitt"
  meta_twitter_creator: "@tillwitt"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
